#NAME: Yuxing Chen / Yuhong Wang
#ID: 
#EMAIL: 

FILES=Makefile README lab3b.py

.SILENT:

default:
	cp lab3b.py lab3b
	chmod +x lab3b

dist:
	tar -czf lab3b-000000000.tar.gz $(FILES)

clean:
	rm -f *.err lab3b *.tar.gz
